### ISSUE TITLE
Proxy Error: Cannot read properties of null (reading 'toString') (see more in sp-rest-proxy console)

### ISSUE THREAD

**Issue by kadut001** [koltyakov/sp-rest-proxy#149]
**Response Error**
{
  "readyState": 4,
  "responseText": "Proxy Error: Cannot read properties of null (reading 'toString') (see more in sp-rest-proxy console)",
  "status": 400,
  "statusText": "Bad Request"
}

<img width="568" alt="porxy-iisue" src="https://user-images.githubusercontent.com/110615295/182904450-93021e21-f3fd-44d5-a9e7-a88314dffb19.PNG">

**Console Log Message**

GET: https://asinspo.sharepoint.us/_api/web/siteusers?
Error TypeError: Cannot read properties of null (reading 'toString')
    at OnDemand.saveAuthData (C:\Users\kofi.adutwum\Documents\Page\sandbox\node_modules\node-sp-auth\lib\src\auth\resolvers\OnDemand\OnDemand.js:83:44)
    at OnDemand.getAuth (C:\Users\kofi.adutwum\Documents\Page\sandbox\node_modules\node-sp-auth\lib\src\auth\resolvers\OnDemand\OnDemand.js:38:28)
    at Object.getAuth (C:\Users\kofi.adutwum\Documents\Page\sandbox\node_modules\node-sp-auth\lib\src\index.js:16:76)
    at SPClient.<anonymous> (C:\Users\kofi.adutwum\Documents\Page\sandbox\node_modules\sp-rest-proxy\dist\utils\client.js:69:51)   
    at step (C:\Users\kofi.adutwum\Documents\Page\sandbox\node_modules\sp-rest-proxy\dist\utils\client.js:44:23)
    at Object.next (C:\Users\kofi.adutwum\Documents\Page\sandbox\node_modules\sp-rest-proxy\dist\utils\client.js:25:53)
    at C:\Users\kofi.adutwum\Documents\Page\sandbox\node_modules\sp-rest-proxy\dist\utils\client.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\kofi.adutwum\Documents\Page\sandbox\node_modules\sp-rest-proxy\dist\utils\client.js:15:12)
    at SPClient.fetch (C:\Users\kofi.adutwum\Documents\Page\sandbox\node_modules\sp-rest-proxy\dist\utils\client.js:65:20)

I'm trying to use on demand electron credentials for this proxy. 
Any solution to this issue?

Thank you!

**Comment by koltyakov** [comment]
Hi @kadut001,

It's definitely auth thing. On-Demand might be picky to Electron version.

Could you try separating concerns by checking auth via https://github.com/koltyakov/node-sp-auth-troubleshoot raw minimal console approach?

If doesn't work please post to auth library repo https://github.com/s-KaiNet/node-sp-auth

**Comment by kadut001** [comment]
Hi @koltyakov,

Thank you. It resolved my problem!

**Comment by smailsw** [comment]
@kadut001 i have the same issue, can you provide me please with your solution ? thank you

**Comment by kadut001** [comment]
Hi @smailsw 

Here are my solution
1. git clone https://github.com/koltyakov/node-sp-auth-troubleshoot
2. cd node-sp-auth-troubleshoot
3. npm install
4. npm run test -- --env uat

I have to run npm run test -- --env uat every 24 hours because the cookies expire but you can put the commands in batch script and have the batch on a scheduler.

Please let me know if it does not work
