### ISSUE TITLE
sp-rest-proxy does not work with Node 18.16.0 (current LTS)

### ISSUE THREAD

**Issue by davea38** [koltyakov/sp-rest-proxy#163]
Hello again!

I've just updated my Windows 10 dev machine to Node 18.16.0 (current LTS) and sp-rest-proxy is throwing errors on all calls.

If I revert the Node version to v16.20.0 then the proxy starts working again with no code change.

My credential strategy is OnpremiseUserCredentials as I am using SP 2013 on-prem.

```powershell
Error Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at Object.createNTLMHash (C:\...\node_modules\node-ntlm-client\lib\hash.js:77:22)
    at Object.createType3Message (C:\...\node_modules\node-ntlm-client\lib\ntlm.js:213:23)
    at C:\...\node_modules\node-sp-auth\lib\src\auth\resolvers\OnpremiseUserCredentials.js:41:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

**Comment by davea38** [comment]
Found a workaround for using v18.16.0:

- Install cross-env 
```powershell
npm i --save-dev cross-env
```
- Alter the package.json script to add in this:
```powershell
cross-env NODE_OPTIONS=--openssl-legacy-provider <proxyLaunch>
```

So for me the package.json line was:
```javascript
{ "proxy": "cross-env NODE_OPTIONS=--openssl-legacy-provider node ./.sp-rest-proxy/server.js", }
```

Of course the other workaround is to revert to using v16.20.0 :)

**Comment by davea38** [comment]
> Found a workaround for using v18.16.0:
> 
> * Install cross-env
> 
> ```powershell
> npm i --save-dev cross-env
> ```
> 
> * Alter the package.json script to add in this:
> 
> ```powershell
> cross-env NODE_OPTIONS=--openssl-legacy-provider <proxyLaunch>
> ```
> 
> So for me the package.json line was:
> 
> ```js
> { "proxy": "cross-env NODE_OPTIONS=--openssl-legacy-provider node ./.sp-rest-proxy/server.js", }
> ```
> 
> Of course the other workaround is to revert to using v16.20.0 :)

Having said all of that using --openssl-legacy-provider still gives socket hang up errors, so the best solution is to revert node version to v16

**Comment by kokoc58** [comment]
sp-rest-proxy does not work with Node 20
"Бен, это Данила айнидхелп...."

**Comment by koltyakov** [comment]
@kokoc58 to run it with Node.js >= 18 you need to start in Node.js process with `NODE_OPTIONS` env variable with `--openssl-legacy-provider`.

```bash
npx cross-env NODE_OPTIONS=--openssl-legacy-provider ts-node ./src/server
```

![image](https://github.com/koltyakov/sp-rest-proxy/assets/7816483/bd78e381-6e19-411e-8d7a-60b7649865cc)

![image](https://github.com/koltyakov/sp-rest-proxy/assets/7816483/90234ad0-8cff-4807-9aa8-698f9b821605)

Alternatively, we can contribute to [node-sp-auth](https://github.com/s-KaiNet/node-sp-auth) e.g. by replacing legacy NTLM client maybe with https://www.npmjs.com/package/@ewsjs/ntlm-client

What auth strategy do you use, Данила? :)

Does is work for you with `NODE_OPTIONS=--openssl-legacy-provider`? If not, what's the error?

**Comment by hillhouseitsolutions-lab** [comment]
Just to confirm (this is a very old bump), but using `NODE_OPTIONS=--openssl-legacy-provider` doesn't work.
