### ISSUE TITLE
Proxy Error: Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by VivekChhatbarBacancy** [koltyakov/sp-rest-proxy#181]
I am encountering a TypeError while Running sp-rest-proxy in my Angular project, which utilizes On-Demand Credentials as the authentication strategy. The error message reads: **`TypeError: Cannot read properties of null (reading 'toString')`**

This issue arises and on-demand authentication doesn't show the browser window.

**Version Information:**
- Angular : ^17.3.0
- Nodejs: 22.0.0
- sp-rest-proxy -> ^3.3.6
- @pnp/sp -> ^4.3.0
- Electron
![image](https://github.com/user-attachments/assets/aeab4420-5989-4752-852f-4671ff70c35a)

**Detailed Error Message**
> node src/sp-proxy.js

(node:12656) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

? SharePoint URL https://tenant.sharepoint.com/sites/mysite
? Authentication strategy On-Demand credentials (Electron@8 is required, not compatible with NTLM)
SharePoint REST Proxy has been started on http://localhost:8080

`GET: https://tenant.sharepoint.com/sites/mysite/_api/web/currentuser`
**Error TypeError: Cannot read properties of null (reading 'toString')**
    at OnDemand.saveAuthData (C:\Users\Vivek\Documents\Projects\portal-idea\node_modules\node-sp-auth\lib\src\auth\resolvers\OnDemand\OnDemand.js:83:44)
    at OnDemand.getAuth (C:\Users\Vivek\Documents\Projects\portal-idea\node_modules\node-sp-auth\lib\src\auth\resolvers\OnDemand\OnDemand.js:38:28)
    at Object.getAuth (C:\Users\Vivek\Documents\Projects\portal-idea\node_modules\node-sp-auth\lib\src\index.js:16:76)
    at SPClient.<anonymous> (C:\Users\Vivek\Documents\Projects\portal-idea\node_modules\sp-rest-proxy\dist\utils\client.js:69:51)
    at step (C:\Users\Vivek\Documents\Projects\portal-idea\node_modules\sp-rest-proxy\dist\utils\client.js:44:23)
    at Object.next (C:\Users\Vivek\Documents\Projects\portal-idea\node_modules\sp-rest-proxy\dist\utils\client.js:25:53)
    at (C:\Users\Vivek\Documents\Projects\portal-idea\node_modules\sp-rest-proxy\dist\utils\client.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Vivek\Documents\Projects\portal-idea\node_modules\sp-rest-proxy\dist\utils\client.js:15:12)
   at SPClient.fetch (C:\Users\Vivek\Documents\Projects\portal-idea\node_modules\sp-rest-proxy\dist\utils\client.js:65:20)

**Comment by koltyakov** [comment]
Hi @VivekChhatbarBacancy,


This is not connected with the library, but the external authentication module [node-sp-auth](https://github.com/s-KaiNet/node-sp-auth).

**Comment by VivekChhatbarBacancy** [comment]
Hello @koltyakov,

Correct the issue is from node-sp-auth, And as a work around I've downgraded the sp-rest-proxy version from **3.3.6** to **2.11.1**
and everything works.
